# Generated by Django 4.2.7 on 2025-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facility_type',
            field=models.CharField(blank=True, default='', help_text='PHC/CHC/District Hospital/etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
